### ISSUE TITLE
Coredump when running

### ISSUE THREAD

**Issue by erikw** [nonpop/xkblayout-state#4]
Since about 2months ago xkblayout coredumps directly when starting for me.

```bash
$ xkblayout-state state
[1]    15645 segmentation fault (core dumped)  xkblayout-state state
$ xkblayout-state
[1]    17560 segmentation fault (core dumped)  xkblayout-state
```

:( 

My system:
OS: Arch 64bit
xkblayout-state: Installed via AUR version `20150804-1  (0.67)`

**Edit.** 

The backtrace is

```gdb
#0  0x0000000000403c14 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__s=0x407270 "en_US", this=0x40) at /usr/include/c++/6.2.1/bits/basic_string.h:1254
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__s=0x407270 "en_US", this=<optimized out>) at /usr/include/c++/6.2.1/bits/basic_string.h:590
#2  XKeyboard::initializeXkb (this=this@entry=0x7ffe16c4b0d0) at XKeyboard.cpp:163
#3  0x00000000004040b8 in XKeyboard::XKeyboard (this=0x7ffe16c4b0d0) at XKeyboard.cpp:56
#4  0x0000000000401e2d in main (argc=1, argv=0x7ffe16c4b238) at wrapper.cpp:164
```

In frame #0 `this` has address `0x40`, is that right? I see in frame `#4` that the vector has no elements but we try to insert to it at an index, which is not right

```c++
while (--k >= 0) _symbolNames[k] = "en_US";
```

```gdb
(gdb) print _symbolNames
$4 = std::vector of length 0, capacity 0
(gdb) print k
$5 = 2
```

Here also

```
int count = _symbolNames.size();  // is 0
```

**Edit 2.**

I remember now that I refactored my [XKB config](https://github.com/erikw/dotfiles/blob/personal/.xkb/keymap.xkb) some months ago.

When `xkb_symbols` are all in one include it works:
```
xkb_keymap "erikwkbrd" {
	xkb_keycodes  { include "evdev+aliases(qwerty)" };
	xkb_types     { include "complete" };
	xkb_compat    { include "complete" };

	xkb_symbols{include"pc+us(basic)+se(basic):2+de(basic):3+hacks+inet(evdev)+group(switch)+group(menu_toggle)+ctrl(nocaps)+compose(rwin)+terminate(ctrl_alt_bksp)"};

	xkb_geometry  { include "pc(pc104)" };
};
```

But when I separate them in to different includes like this:

```
xkb_keymap "erikwkbrd" {
	xkb_keycodes  { include "evdev+aliases(qwerty)" };
	xkb_types     { include "complete" };
	xkb_compat    { include "complete" };

	xkb_symbols   {
		include "pc"				
		include "us(basic)"			
		include "se(basic):2"			
		include "de(basic):3"			
		include "hacks"				
		include "inet(evdev)"			
		include "group(switch)"			
		include "group(menu_toggle)"		
		include "ctrl(nocaps)"			
		include "compose(rwin)"			
		include "terminate(ctrl_alt_bksp)"	
	};

	xkb_geometry  { include "pc(pc104)" };
};
```

xkblayout-state coredumps. I think the latter configuration is valid. It works keyboard-wise at least. But having it split up like this apparently confuses xkblayout-state it seems?

**Comment by nonpop** [comment]
I get the same segfault. I'll look at it when I have more time. Or if you fix it, please share!
